<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title><?php echo esc_html($title); ?></title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            line-height: 1.6;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
        }
        .post {
            margin-bottom: 30px;
            page-break-inside: avoid;
        }
        .post-title {
            color: #2c3338;
            font-size: 18px;
            margin-bottom: 10px;
        }
        .post-meta {
            color: #666;
            font-size: 12px;
            margin-bottom: 15px;
        }
        .post-excerpt {
            margin-bottom: 15px;
        }
        .footer {
            text-align: center;
            font-size: 12px;
            margin-top: 30px;
            border-top: 1px solid #333;
            padding-top: 20px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1><?php echo esc_html($title); ?></h1>
        <p>Weekly Newsletter - <?php echo date('F j, Y'); ?></p>
    </div>

    <?php foreach ($posts as $post): ?>
        <?php $meta = (new PostCollector())->get_post_meta_data($post); ?>
        <div class="post">
            <h2 class="post-title"><?php echo esc_html($meta['title']); ?></h2>
            
            <div class="post-meta">
                By <?php echo esc_html($meta['author']); ?> | 
                <?php echo esc_html($meta['date']); ?>
            </div>
            
            <div class="post-excerpt">
                <?php echo wp_kses_post($meta['excerpt']); ?>
            </div>
        </div>
    <?php endforeach; ?>

    <div class="footer">
        <p>Generated by Weekly Post Newsletter Plugin</p>
    </div>
</body>
</html> 